(() => {
  const root = document.getElementById('app-content');
  const sidebar = document.getElementById('sidebar');
  const modal = document.getElementById('modal');
  const modalBox = modal?.querySelector('.modal');

  const professionals = ['Dott. Luca Bianchi', 'Dott.ssa Chiara Ferri'];
  const treatments = [
    ['Fisioterapia', 60], ['Tecar', 45], ['Laser', 60], ['Riabilitazione', 60]
  ];
  const labels = { pending: 'Da confermare', confirmed: 'Confermato', completed: 'Completato', cancelled: 'Cancellato', noshow: 'No-show' };
  const colors = { Fisioterapia: 'blue', Tecar: 'violet', Laser: 'violet', Riabilitazione: 'green' };
  const state = { view: 'dashboard', date: new Date('2026-09-02T12:00:00'), professional: 'Tutti' };
  let nextId = 10;
  let data = [
    {id:1,date:'2026-09-02',time:'09:00',patient:'Mario Rossi',treatment:'Fisioterapia',professional:professionals[0],status:'completed'},
    {id:2,date:'2026-09-02',time:'10:00',patient:'Anna Esposito',treatment:'Tecar',professional:professionals[1],status:'confirmed'},
    {id:3,date:'2026-09-02',time:'12:00',patient:'Giuseppe Romano',treatment:'Laser',professional:professionals[1],status:'pending'},
    {id:4,date:'2026-09-02',time:'14:00',patient:'Francesca Russo',treatment:'Riabilitazione',professional:professionals[0],status:'confirmed'},
    {id:5,date:'2026-09-03',time:'09:30',patient:'Marco De Luca',treatment:'Fisioterapia',professional:professionals[0],status:'pending'},
    {id:6,date:'2026-09-04',time:'11:00',patient:'Laura Esposito',treatment:'Tecar',professional:professionals[1],status:'confirmed'}
  ];

  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const iso = d => d.toISOString().slice(0,10);
  const plusDays = (d,n) => { const x=new Date(d); x.setDate(x.getDate()+n); return x; };
  const mins = t => { const [h,m]=t.split(':').map(Number); return h*60+m; };
  const time = n => `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
  const dateLong = d => new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'}).format(d);
  const dayName = d => new Intl.DateTimeFormat('it-IT',{weekday:'short'}).format(d).replace('.','');

  function setHeader(section,title){ document.getElementById('breadcrumb').textContent=section; document.getElementById('page-title').textContent=title; }
  function head(kicker,title,lead,button=true){ return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p class="lead">${lead}</p></div>${button?'<button class="primary" data-new-appointment>+ Nuovo appuntamento</button>':''}</div>`; }
  function chip(a){ return `<span class="status-chip ${a.status}">${labels[a.status]}</span>`; }

  function dashboard(){
    const today='2026-09-02', todays=data.filter(a=>a.date===today&&a.status!=='cancelled'), pending=data.filter(a=>a.status==='pending');
    return `${head('CONTROL CENTER','Buon pomeriggio.','Ecco cosa succede oggi al Centro Medico Bruniano.')}
      <div class="stats"><article class="stat-card"><span>OGGI</span><strong>${todays.length}</strong><small>appuntamenti</small><em>Agenda attiva</em></article><article class="stat-card"><span>IN ATTESA</span><strong>${pending.length}</strong><small>da confermare</small><em class="neutral">Da gestire</em></article><article class="stat-card"><span>DISPONIBILITÀ</span><strong>${Math.max(0,16-todays.length)}</strong><small>slot indicativi oggi</small><em class="neutral">Tra i professionisti</em></article><article class="stat-card"><span>NUOVI PAZIENTI</span><strong>6</strong><small>questa settimana</small><em>↑ 18%</em></article></div>
      <div class="grid-main"><section class="panel agenda-preview"><div class="panel-head"><div><span class="eyebrow">AGENDA</span><h2>Oggi · Mercoledì 2 settembre</h2></div><button class="text-button" data-view-link="agenda">Apri agenda →</button></div><div class="timeline">${todays.map(a=>`<div class="time-row"><time>${a.time}</time><button class="slot busy ${colors[a.treatment]||'blue'}" data-id="${a.id}"><span class="slot-line"></span><div><strong>${esc(a.patient)}</strong><small>${esc(a.treatment)} · ${esc(a.professional)}</small></div><b>${a.time}–${time(mins(a.time)+(treatments.find(x=>x[0]===a.treatment)?.[1]||60))}</b></button></div>`).join('')}<div class="time-row"><time>11:00</time><button class="slot free" data-new-time="11:00"><span class="slot-line"></span><div><strong>Slot disponibile</strong><small>Dott. Luca Bianchi</small></div><button class="mini" data-new-time="11:00">Prenota</button></button></div></div></section><aside class="side-stack"><section class="panel quick-panel"><div class="panel-head"><div><span class="eyebrow">DA FARE</span><h2>Attività</h2></div><span class="counter">${pending.length}</span></div><button class="task" data-view-link="appointments"><span class="task-dot amber"></span><div><strong>Confermare appuntamenti</strong><small>${pending.length} richieste in attesa</small></div><b>→</b></button><button class="task" data-view-link="reviews"><span class="task-dot green-dot"></span><div><strong>Recensioni</strong><small>Gestisci la presenza Google</small></div><b>→</b></button></section><section class="panel today-card"><span class="eyebrow">PROSSIMO</span>${todays[0]?`<strong>${esc(todays[0].patient)}</strong><small>${esc(todays[0].treatment)} · ${todays[0].time}</small>`:'<strong>Agenda libera</strong><small>Nessun appuntamento</small>'}<div class="progress"><span style="width:58%"></span></div><small>Vista operativa di oggi</small></section></aside></div>
      <section class="panel recent"><div class="panel-head"><div><span class="eyebrow">ATTIVITÀ RECENTI</span><h2>Ultime operazioni</h2></div></div><div class="activity-list"><div><span class="activity-avatar">MR</span><p><strong>Mario Rossi</strong> · appuntamento completato<small>oggi, 08:42</small></p><b>Agenda</b></div><div><span class="activity-avatar blue-bg">CF</span><p><strong>Chiara Ferri</strong> ha modificato un appuntamento<small>oggi, 08:31</small></p><b>Agenda</b></div></div></section>`;
  }

  function agenda(){
    const base=new Date(state.date); const monday=new Date(base); const wd=monday.getDay()||7; monday.setDate(monday.getDate()-wd+1); const days=[0,1,2,3,4].map(n=>plusDays(monday,n)); const hours=Array.from({length:10},(_,i)=>8+i);
    const filtered=data.filter(a=>state.professional==='Tutti'||a.professional===state.professional);
    const eventsByDay=d=>filtered.filter(a=>a.date===iso(d));
    return `${head('AGENDA OPERATIVA','Agenda','Organizza la giornata, controlla le disponibilità e gestisci gli appuntamenti.')}
      <section class="panel agenda-toolbar"><div class="toolbar-left"><button class="seg active">Settimana</button><button class="seg">Giorno</button><button class="nav-arrow" data-shift="-5">←</button><button class="nav-arrow" data-shift="5">→</button><button class="today-btn" data-today>Oggi</button><strong>${dateLong(state.date)}</strong></div><div class="toolbar-right"><label class="filter-label">Professionista<select id="agenda-professional"><option>Tutti</option>${professionals.map(p=>`<option ${p===state.professional?'selected':''}>${p}</option>`).join('')}</select></label></div></section>
      <section class="panel agenda-card"><div class="agenda-weekhead"><div class="week-spacer"></div>${days.map(d=>`<div class="day-head-cell ${iso(d)===iso(state.date)?'selected':''}"><small>${dayName(d)}</small><strong>${d.getDate()}</strong></div>`).join('')}</div><div class="agenda-body"><div class="time-col">${hours.map(h=>`<span>${String(h).padStart(2,'0')}:00</span>`).join('')}</div><div class="calendar-grid">${days.map(d=>`<div class="day-column">${hours.map(h=>`<div class="grid-slot" data-new-date="${iso(d)}" data-new-time="${String(h).padStart(2,'0')}:00"></div>`).join('')}${eventsByDay(d).map(a=>`<button class="calendar-event ${colors[a.treatment]||'blue'} ${a.status}" style="--row:${Math.max(1,hourRow(a.time))};--span:${Math.max(1,Math.ceil((duration(a.treatment)||60)/60))}" data-id="${a.id}"><span>${a.time}</span><strong>${esc(a.patient)}</strong><small>${esc(a.treatment)}</small></button>`).join('')}</div>`).join('')}</div></div></section><div class="agenda-legend"><span><i class="legend-dot blue"></i>Confermato</span><span><i class="legend-dot amber"></i>Da confermare</span><span><i class="legend-dot green"></i>Completato</span><span class="legend-note">Clicca su uno slot libero per prenotare</span></div>`;
  }
  function hourRow(t){return Math.floor(mins(t)/60)-7;}
  function duration(t){return treatments.find(x=>x[0]===t)?.[1]||60;}

  function appointments(){ return `${head('OPERATIVITÀ','Appuntamenti','Richieste, conferme e storico operativo del centro.')}
    <section class="panel filters-panel"><div class="search-box"><span>⌕</span><input id="appt-search" placeholder="Cerca paziente, trattamento o professionista…"></div><select id="appt-status"><option value="all">Tutti gli stati</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><button class="secondary" id="export-appt">Esporta</button></section>
    <section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">AGENDA</span><h2>Tutti gli appuntamenti</h2></div><span class="counter">${data.length}</span></div><div class="table-wrap"><table><thead><tr><th>Data / ora</th><th>Paziente</th><th>Trattamento</th><th>Professionista</th><th>Stato</th><th></th></tr></thead><tbody id="appt-body">${rows(data)}</tbody></table></div></section>`; }
  function rows(list){ return list.map(a=>`<tr><td><strong>${a.time}</strong><small>2 settembre</small></td><td><strong>${esc(a.patient)}</strong><small>Anagrafica</small></td><td>${esc(a.treatment)}</td><td>${esc(a.professional)}</td><td>${chip(a)}</td><td><button class="row-action" data-id="${a.id}">Apri</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty-state">Nessun risultato.</div></td></tr>'; }

  const other={
    patients:['ANAGRAFICA','Pazienti','Anagrafica gestionale minima, separata da eventuali dati clinici.'], professionals:['TEAM','Professionisti','Professionisti, disponibilità e collegamento con l’agenda.'], treatments:['SERVIZI','Trattamenti','Catalogo dei servizi, durata e regole di prenotazione.'], promotions:['COMMERCIALE','Promozioni','Offerte pubblicate sul sito e relative finestre di validità.'], content:['CONTENUTI','Sito e contenuti','Accesso ordinato a Studio, Blog e media.'], reviews:['FIDUCIA','Recensioni','Presenza Google e gestione delle informazioni pubbliche.'], users:['SICUREZZA','Utenti e ruoli','Accessi, ruoli, inviti e permessi del personale.'], settings:['CONFIGURAZIONE','Impostazioni','Configurazioni operative del centro.']
  };
  function otherView(v){ const x=other[v]; return `${head(x[0],x[1],x[2],false)}<div class="module-grid"><article class="module-card"><span class="eyebrow">STRUTTURA</span><h3>Modulo predisposto</h3><p>La sezione è pronta per essere collegata al modello dati definitivo, senza modificare il sito pubblico.</p><button class="secondary" data-view-link="dashboard">Torna alla dashboard</button></article><article class="module-card"><span class="eyebrow">STAGING</span><h3>Ambiente di test</h3><p>Nessun dato reale viene scritto in questa fase.</p></article><article class="module-card"><span class="eyebrow">PROSSIMO PASSO</span><h3>Integrazione</h3><p>La logica verrà collegata dopo aver definito ruoli, database e flussi operativi.</p></article></div>`; }

  function show(v){ state.view=v; const t={dashboard:['Dashboard','Panoramica'],agenda:['Agenda','Agenda'],appointments:['Agenda','Gestione appuntamenti'],...Object.fromEntries(Object.entries(other).map(([k,x])=>[k,[x[0],x[1]]]))}[v]||['Dashboard','Panoramica']; setHeader(t[0],t[1]); root.innerHTML=v==='dashboard'?dashboard():v==='agenda'?agenda():v==='appointments'?appointments():otherView(v); sidebar?.classList.remove('open'); bind(); }
  function bind(){
    document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view)); document.querySelectorAll('[data-view-link]').forEach(b=>b.onclick=()=>show(b.dataset.viewLink)); document.querySelectorAll('[data-new-appointment]').forEach(b=>b.onclick=()=>openModal()); document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openModal(data.find(a=>a.id===Number(b.dataset.id))));
    document.querySelectorAll('[data-new-time]').forEach(b=>b.onclick=e=>{e.stopPropagation();openModal({date:b.dataset.newDate||'2026-09-02',time:b.dataset.newTime||'11:00'});});
    document.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{state.date=plusDays(state.date,Number(b.dataset.shift));show('agenda');}); document.querySelector('[data-today]')?.addEventListener('click',()=>{state.date=new Date('2026-09-02T12:00:00');show('agenda');});
    document.getElementById('agenda-professional')?.addEventListener('change',e=>{state.professional=e.target.value;show('agenda');});
    document.getElementById('appt-search')?.addEventListener('input',filterAppointments); document.getElementById('appt-status')?.addEventListener('change',filterAppointments);
    document.getElementById('export-appt')?.addEventListener('click',()=>alert('Esportazione disponibile nella fase collegata al database.'));
  }
  function filterAppointments(){ const q=(document.getElementById('appt-search')?.value||'').toLowerCase(); const s=document.getElementById('appt-status')?.value||'all'; const list=data.filter(a=>(s==='all'||a.status===s)&&`${a.patient} ${a.treatment} ${a.professional}`.toLowerCase().includes(q)); const body=document.getElementById('appt-body'); if(body){body.innerHTML=rows(list);body.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openModal(data.find(a=>a.id===Number(b.dataset.id))));} }

  function openModal(existing={}){ const isEdit=!!existing.id; const a={date:'2026-09-02',time:'11:00',patient:'',professional:professionals[0],treatment:treatments[0][0],status:'pending',...existing}; modalBox.innerHTML=`<button class="modal-close" id="modal-close">×</button><span class="eyebrow">${isEdit?'MODIFICA APPUNTAMENTO':'NUOVO APPUNTAMENTO'}</span><h2>${isEdit?esc(a.patient):'Prenota un appuntamento'}</h2><p class="modal-intro">Ambiente di sviluppo: i dati restano temporanei nel browser.</p><form id="appt-form"><label>Paziente<input name="patient" value="${esc(a.patient)}" placeholder="Nome e cognome" required></label><div class="form-grid"><label>Data<input name="date" type="date" value="${a.date}" required></label><label>Ora<input name="time" type="time" value="${a.time}" required></label></div><div class="form-grid"><label>Professionista<select name="professional">${professionals.map(p=>`<option ${p===a.professional?'selected':''}>${p}</option>`).join('')}</select></label><label>Trattamento<select name="treatment">${treatments.map(t=>`<option value="${esc(t[0])}" ${t[0]===a.treatment?'selected':''}>${t[0]} · ${t[1]} min</option>`).join('')}</select></label></div><label>Note<textarea name="notes" rows="3" placeholder="Note operative…"></textarea></label><div class="modal-actions"><button type="button" class="secondary" id="modal-cancel">Annulla</button><button class="primary">${isEdit?'Salva modifiche':'Salva appuntamento'}</button></div></form>`; modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); document.getElementById('modal-close').onclick=closeModal; document.getElementById('modal-cancel').onclick=closeModal; document.getElementById('appt-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const item={date:f.get('date'),time:f.get('time'),patient:f.get('patient').trim(),professional:f.get('professional'),treatment:f.get('treatment'),status:isEdit?a.status:'pending'};if(isEdit)data=data.map(x=>x.id===a.id?{...x,...item}:x);else data.push({id:nextId++,...item});closeModal();show(state.view);}; }
  function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');}
  document.getElementById('mobile-menu')?.addEventListener('click',()=>sidebar?.classList.toggle('open')); document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
  show(location.hash.replace('#','')||'dashboard');
})();
