(async function(){
  const favicon=document.createElement('link');favicon.rel='icon';favicon.type='image/svg+xml';favicon.href='../assets/favicon.svg?v=20260903';document.head.appendChild(favicon);
  document.documentElement.style.visibility='hidden';
  try{
    const session=await fetch('/api/auth',{credentials:'same-origin',cache:'no-store'});if(!session.ok)throw new Error('unauthorized');
    const auth=await session.json();if(auth.must_change_password){window.location.replace('login.html?change=1');return;}
    const fullName=[auth.first_name,auth.last_name].filter(Boolean).join(' ').trim()||(auth.username==='admin'?'Amministratore':auth.username||'Operatore');
    if(document.getElementById('user-name'))document.getElementById('user-name').textContent=fullName;
    if(document.getElementById('dashboard-user-name'))document.getElementById('dashboard-user-name').textContent=fullName;
    if(document.getElementById('user-role'))document.getElementById('user-role').textContent=auth.username==='admin'?'Accesso completo':'Operatore';
    if(document.getElementById('user-avatar'))document.getElementById('user-avatar').textContent=fullName.charAt(0).toUpperCase();
    setDashboardGreeting();document.documentElement.style.visibility='visible';
  }catch{window.location.replace('login.html');return;}

  function setDashboardGreeting(){const el=document.getElementById('dashboard-greeting');if(!el)return;const hour=new Date().getHours();let greeting='Buonasera';if(hour>=5&&hour<12)greeting='Buongiorno';else if(hour>=12&&hour<18)greeting='Buon pomeriggio';else if(hour<5)greeting='Buonanotte';el.textContent=greeting;}
  const state={blog:[],gallery:[]};const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]));
  async function logout(){try{await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({action:'logout'})});}finally{window.location.replace('login.html');}}
  async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',headers:{'content-type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(r.status===401){window.location.replace('login.html');throw new Error('Sessione scaduta');}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
  function setStatus(message,error=false){const el=$('system-status');if(!el)return;el.textContent=message;el.classList.toggle('ok',!error)}
  function activatePanel(name){document.querySelectorAll('.dash-card').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${name}`));if(name==='blog')window.dispatchEvent(new CustomEvent('bruniano:blog-open'));}
  document.querySelectorAll('.dash-card').forEach(btn=>btn.addEventListener('click',()=>activatePanel(btn.dataset.panel)));
  function setupChecks(){fetch('/api/health',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(()=>setStatus('Backend collegato')).catch(()=>setStatus('Backend non disponibile',true));if($('last-check'))$('last-check').textContent=new Date().toLocaleString('it-IT');}

  function autoSlug(title){return String(title||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,180);}
  function plainContent(){const html=$('blog-content')?.innerHTML||'';const box=document.createElement('div');box.innerHTML=html;return (box.textContent||'').replace(/\s+/g,' ').trim();}
  function buildMeta(){const manual=String($('blog-meta')?.dataset.manual||'').trim();if(manual)return manual;const title=String($('blog-title')?.value||'').trim();const excerpt=String($('blog-excerpt')?.value||'').trim();const content=plainContent();let text=excerpt||content;const category=String($('blog-category')?.value||'').trim();if(category&&!text.toLowerCase().includes(category.toLowerCase()))text=`${category}: ${text}`;text=text.replace(/\s+/g,' ').trim();const suffix='Scopri di più sul Centro Medico Specialistico Bruniano.';let meta=`${title}${text?` — ${text}`:''}`.trim();if(meta.length>155)meta=meta.slice(0,152).replace(/\s+\S*$/,'').trim()+'…';if(!meta&&suffix)meta=suffix.slice(0,155);return meta;}
  function updateBlogSEO(){const title=$('blog-title')?.value||'';const slug=$('blog-slug');if(slug&&!slug.dataset.manual)slug.value=autoSlug(title);const meta=$('blog-meta');if(meta&&!meta.dataset.manual)meta.value=buildMeta();const titleCount=$('blog-title-count');if(titleCount)titleCount.textContent=`${title.length}/200`;const metaCount=$('blog-meta-count');if(metaCount)metaCount.textContent=`${String(meta?.value||'').length}/160`;const excerptCount=$('blog-excerpt-count');if(excerptCount)excerptCount.textContent=`${String($('blog-excerpt')?.value||'').length}/300`;updateBlogPreview();}
  function updateBlogPreview(){const title=String($('blog-title')?.value||'Titolo dell’articolo').trim()||'Titolo dell’articolo';const category=String($('blog-category')?.value||'Fisioterapia').trim()||'Fisioterapia';const author=String($('blog-author')?.value||'Bruniano').trim()||'Bruniano';const text=plainContent()||String($('blog-excerpt')?.value||'').trim()||'L’anteprima dell’articolo apparirà qui mentre scrivi.';const cover=$('blog-cover')?.value||'';if($('blog-preview-title'))$('blog-preview-title').textContent=title;if($('blog-preview-category'))$('blog-preview-category').textContent=category;if($('blog-preview-author'))$('blog-preview-author').textContent=author;if($('blog-preview-text'))$('blog-preview-text').textContent=text.slice(0,260)+(text.length>260?'…':'');const img=$('blog-preview-image');if(img){if(cover){img.src=cover;img.classList.add('is-visible');}else{img.removeAttribute('src');img.classList.remove('is-visible');}}const score=$('blog-seo-score');if(score){let points=0;if(title.length>=30&&title.length<=70)points+=20;else if(title)points+=10;if(String($('blog-meta')?.value||'').length>=100&&String($('blog-meta')?.value||'').length<=160)points+=20;else if($('blog-meta')?.value)points+=10;if($('blog-cover')?.value)points+=20;if(plainContent().length>=600)points+=20;else if(plainContent())points+=10;if($('blog-category')?.value)points+=10;if($('blog-slug')?.value)points+=10;score.textContent=`${points}/100`;score.className=`blog-seo-score score-${points>=80?'good':points>=50?'mid':'low'}`;}}
  function setupBlogEditor(){const form=$('blog-form'),content=$('blog-content');if(!form||!content||form.dataset.enhanced)return;form.dataset.enhanced='1';
    ['blog-title','blog-category','blog-author','blog-excerpt','blog-content','blog-cover','blog-slug','blog-meta'].forEach(id=>$(id)?.addEventListener('input',()=>{if(id==='blog-slug')$(id).dataset.manual='1';if(id==='blog-meta')$(id).dataset.manual='1';updateBlogSEO();}));
    if($('blog-cover'))$('blog-cover').addEventListener('change',updateBlogSEO);
    const toolbar=document.createElement('div');toolbar.className='blog-editor-toolbar';toolbar.setAttribute('aria-label','Strumenti di formattazione');toolbar.innerHTML=[['bold','B','Grassetto'],['italic','I','Corsivo'],['underline','U','Sottolineato'],['formatBlock','H2','Titolo'],['insertUnorderedList','•','Elenco'],['insertOrderedList','1.','Elenco numerato'],['blockquote','“','Citazione']].map(([cmd,label,title])=>`<button type="button" data-command="${cmd}" title="${title}" aria-label="${title}">${label}</button>`).join('')+`<span class="blog-editor-spacer"></span><span class="blog-editor-hint">Scrivi il contenuto dell’articolo</span>`;content.parentNode.insertBefore(toolbar,content);toolbar.addEventListener('click',event=>{const btn=event.target.closest('[data-command]');if(!btn)return;content.focus();const cmd=btn.dataset.command;if(cmd==='formatBlock')document.execCommand('formatBlock',false,'<h2>');else if(cmd==='blockquote')document.execCommand('formatBlock',false,'<blockquote>');else document.execCommand(cmd,false,null);updateBlogSEO();});
    const coverLabel=$('blog-cover')?.closest('label');if(coverLabel){const note=document.createElement('div');note.className='blog-cover-preview';note.innerHTML='<div class="blog-cover-empty">Nessuna immagine selezionata</div><img id="blog-cover-preview" alt="Anteprima copertina" loading="lazy">';coverLabel.appendChild(note);}
    const metaLabel=$('blog-meta')?.closest('label');if(metaLabel){metaLabel.classList.add('blog-seo-field');const row=document.createElement('div');row.className='blog-field-counts';row.innerHTML='<span id="blog-meta-count">0/160</span><span>Generata automaticamente · modificabile</span>';metaLabel.appendChild(row);}
    const titleLabel=$('blog-title')?.closest('label');if(titleLabel){const row=document.createElement('div');row.className='blog-field-counts';row.innerHTML='<span id="blog-title-count">0/200</span><span>Titolo SEO consigliato: 30–70 caratteri</span>';titleLabel.appendChild(row);}
    const excerptLabel=$('blog-excerpt')?.closest('label');if(excerptLabel){const row=document.createElement('div');row.className='blog-field-counts';row.innerHTML='<span id="blog-excerpt-count">0/300</span><span>Usato anche per le anteprime</span>';excerptLabel.appendChild(row);}
    const publish=$('blog-is-published')?.closest('label');if(publish)publish.classList.add('sr-only-control');
    const side=document.querySelector('#panel-blog .blog-layout>div:nth-child(2)');if(side){const publishCard=document.createElement('section');publishCard.className='blog-publish-card';publishCard.innerHTML='<div class="blog-side-kicker">PUBBLICAZIONE</div><h3>Pronto per il sito?</h3><p>La SEO viene preparata automaticamente. Puoi pubblicare subito oppure salvare l’articolo come bozza.</p><div class="blog-status-line"><span class="blog-status-dot"></span><span id="blog-publish-status">Bozza</span></div><div class="blog-publish-actions"><button type="button" class="mini" id="blog-save-draft">Salva bozza</button><button type="button" class="primary" id="blog-publish-now">Pubblica articolo</button></div></section>';side.insertBefore(publishCard,side.firstChild);const preview=document.createElement('section');preview.className='blog-live-preview';preview.innerHTML='<div class="blog-side-kicker">ANTEPRIMA</div><div class="blog-preview-image"><div class="blog-preview-image-empty">Cover dell’articolo</div><img id="blog-preview-image" alt=""></div><span class="blog-preview-category" id="blog-preview-category">Fisioterapia</span><h3 id="blog-preview-title">Titolo dell’articolo</h3><div class="blog-preview-meta">Di <span id="blog-preview-author">Bruniano</span></div><p id="blog-preview-text">L’anteprima dell’articolo apparirà qui mentre scrivi.</p><div class="blog-preview-seo"><div><span>SEO SCORE</span><strong id="blog-seo-score" class="blog-seo-score score-low">0/100</strong></div><small>La valutazione è indicativa e aiuta a completare l’articolo.</small></div></section>';side.insertBefore(preview,publishCard.nextSibling);}
    const actions=$('blog-form')?.querySelector('.form-actions');if(actions){actions.classList.add('blog-form-actions');const primary=actions.querySelector('.primary');if(primary)primary.textContent='Salva articolo';}
    $('blog-save-draft')?.addEventListener('click',()=>{if($('blog-is-published'))$('blog-is-published').checked=false;form.requestSubmit();});$('blog-publish-now')?.addEventListener('click',()=>{if($('blog-is-published'))$('blog-is-published').checked=true;if($('blog-published-at')&&!$('blog-published-at').value)$('blog-published-at').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);form.requestSubmit();});$('blog-content')?.setAttribute('data-placeholder','Inizia a scrivere l’articolo…');updateBlogSEO();window.addEventListener('bruniano:blog-open',()=>updateBlogSEO());}
  function renderBlog(){const list=$('blog-list');if(!list)return;list.innerHTML=state.blog.length?state.blog.map(p=>`<div class="managed-item"><div><strong>${esc(p.title)}</strong><small>${esc(p.category||'Senza categoria')} · ${p.is_published?'Pubblicato':'Bozza'}</small></div><div class="managed-actions"><button class="mini" data-edit-post="${p.id}">Modifica</button><button class="mini" data-delete-post="${p.id}">Elimina</button></div></div>`).join(''):'<div class="form-card note">Nessun articolo presente.</div>';}
  function resetPostForm(){if(!$('blog-form'))return;$('blog-form').reset();if($('blog-id'))$('blog-id').value='';if($('blog-content'))$('blog-content').innerHTML='';if($('blog-slug'))$('blog-slug').dataset.manual='';if($('blog-meta'))$('blog-meta').dataset.manual='';if($('blog-cover-status'))$('blog-cover-status').textContent='Scegli una foto dal tuo dispositivo. Verrà caricata automaticamente su Cloudinary e collegata all’articolo.';if($('blog-cover-preview')){$('blog-cover-preview').removeAttribute('src');$('blog-cover-preview').classList.remove('is-visible');}$('blog-publish-status')?$('blog-publish-status').textContent='Bozza':null;updateBlogSEO();if($('blog-form-status'))$('blog-form-status').textContent=''}
  function fillPostForm(p){if(!$('blog-id'))return;$('blog-id').value=p.id;$('blog-title').value=p.title||'';$('blog-category').value=p.category||'';$('blog-author').value=p.author||'';$('blog-published-at').value=p.published_at?new Date(p.published_at).toISOString().slice(0,16):'';$('blog-slug').value=p.slug||'';$('blog-slug').dataset.manual=p.slug?'1':'';$('blog-excerpt').value=p.excerpt||'';$('blog-content').innerHTML=p.content||'';$('blog-cover').value=p.cover_image_url||'';$('blog-meta').value=p.meta_description||'';$('blog-meta').dataset.manual=p.meta_description?'1':'';$('blog-is-published').checked=Boolean(p.is_published);if($('blog-publish-status'))$('blog-publish-status').textContent=p.is_published?'Pubblicato':'Bozza';if($('blog-cover-preview')){if(p.cover_image_url){$('blog-cover-preview').src=p.cover_image_url;$('blog-cover-preview').classList.add('is-visible');}else{$('blog-cover-preview').removeAttribute('src');$('blog-cover-preview').classList.remove('is-visible');}}activatePanel('blog');updateBlogSEO();}
  async function loadBlog(){setupBlogEditor();try{const d=await api('/api/blog?admin=1');state.blog=d.items||[];renderBlog()}catch(e){renderBlog();setStatus('Blog non disponibile',true)}}
  async function savePost(e){e.preventDefault();const status=$('blog-form-status');if(!status)return;status.textContent='Salvataggio…';updateBlogSEO();const payload={id:$('blog-id')?.value||undefined,title:$('blog-title')?.value||'',category:$('blog-category')?.value||'',author:$('blog-author')?.value||'',published_at:$('blog-published-at')?.value||null,slug:$('blog-slug')?.value||'',excerpt:$('blog-excerpt')?.value||'',content:$('blog-content')?.innerHTML.trim()||'',cover_image_url:$('blog-cover')?.value||'',meta_description:$('blog-meta')?.value||'',is_published:$('blog-is-published')?.checked||false};try{const saved=await api('/api/blog',{method:payload.id?'PUT':'POST',body:JSON.stringify(payload)});const i=state.blog.findIndex(x=>x.id===saved.id);if(i>=0)state.blog[i]=saved;else state.blog.unshift(saved);renderBlog();status.textContent=saved.is_published?'Articolo pubblicato':'Bozza salvata';if($('blog-publish-status'))$('blog-publish-status').textContent=saved.is_published?'Pubblicato':'Bozza';setStatus('Backend collegato');}catch(e){status.textContent=e.message;setStatus('Errore backend',true)}}
  async function deletePost(id){if(!confirm('Eliminare definitivamente questo articolo?'))return;try{await api('/api/blog',{method:'DELETE',body:JSON.stringify({id})});state.blog=state.blog.filter(x=>x.id!==id);renderBlog();resetPostForm()}catch(e){alert(e.message)}}
  $('new-post')?.addEventListener('click',()=>{resetPostForm();activatePanel('blog');$('blog-title')?.focus()});$('cancel-post')?.addEventListener('click',resetPostForm);$('blog-form')?.addEventListener('submit',savePost);$('blog-list')?.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-post]'),del=e.target.closest('[data-delete-post]');if(edit){const p=state.blog.find(x=>x.id===edit.dataset.editPost);if(p)fillPostForm(p)}if(del)deletePost(del.dataset.deletePost)});
  function renderGallery(){const list=$('gallery-list');if(!list)return;const filter=$('gallery-filter')?.value||'all';let items=state.gallery;if(filter==='published')items=items.filter(x=>x.is_published);if(filter==='draft')items=items.filter(x=>!x.is_published);if($('count-gallery'))$('count-gallery').textContent=state.gallery.filter(x=>x.is_published).length;list.innerHTML=items.length?items.map(m=>{const video=String(m.media_type).startsWith('video');return `<article class="media-admin-card"><div class="media-preview">${video?`<video src="${esc(m.media_url)}" muted loop playsinline></video>`:`<img src="${esc(m.media_url)}" alt="${esc(m.alt_text||m.title||'Media Bruniano')}">`}</div><div class="media-admin-body"><strong>${esc(m.title||'Media Bruniano')}</strong><small>${video?'Video':'Foto'} · ${m.is_published?'Pubblicato':'Bozza'}</small><div class="media-admin-actions"><span class="media-status ${m.is_published?'':'draft'}">${m.is_published?'ONLINE':'BOZZA'}</span><button class="mini" data-gallery-toggle="${m.id}">${m.is_published?'Nascondi':'Pubblica'}</button><button class="mini" data-gallery-delete="${m.id}">Elimina</button></div></div></article>`}).join(''):'<div class="form-card note">Nessun media corrisponde al filtro.</div>'}
  async function loadGallery(){try{const d=await api('/api/gallery?admin=1');state.gallery=d.items||[];renderGallery();setStatus('Backend collegato')}catch(e){if($('gallery-list'))$('gallery-list').innerHTML='<div class="form-card note">Impossibile caricare la galleria.</div>';setStatus('Galleria non disponibile',true)}}
  async function saveDroppedGallery(files){
    if(!files?.length)return;
    try{
      if(!window.BrunianoCloudinary){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='cloudinary-upload.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
      if(!window.BrunianoCloudinary?.uploadFiles)throw new Error('Caricamento diretto non disponibile');
      if($('gallery-status'))$('gallery-status').textContent='Caricamento foto e video…';
      await window.BrunianoCloudinary.uploadFiles(files,async info=>{
        try{
          await api('/api/gallery',{method:'POST',body:JSON.stringify({title:info.original_filename||info.display_name||'Media Bruniano',media_type:info.resource_type||'image',media_url:info.secure_url||info.url,alt_text:info.original_filename||'Media Bruniano',is_published:false})});
        }catch(e){if($('gallery-status'))$('gallery-status').textContent=e.message;throw e;}
      });
      if($('gallery-status'))$('gallery-status').textContent='Media caricati e salvati come bozze';
      await loadGallery();
    }catch(e){if($('gallery-status'))$('gallery-status').textContent=e.message||'Impossibile caricare i file.';}
  }
  async function uploadGallery(){try{if(!window.BrunianoCloudinary){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='cloudinary-upload.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}if($('gallery-status'))$('gallery-status').textContent='Apertura caricamento…';await window.BrunianoCloudinary.uploadMedia(async info=>{try{await api('/api/gallery',{method:'POST',body:JSON.stringify({title:info.original_filename||info.display_name||'Media Bruniano',media_type:info.resource_type||'image',media_url:info.secure_url||info.url,alt_text:info.original_filename||'Media Bruniano',is_published:false})});if($('gallery-status'))$('gallery-status').textContent='Media caricato e salvato come bozza';await loadGallery()}catch(e){if($('gallery-status'))$('gallery-status').textContent=e.message}})}catch(e){if($('gallery-status'))$('gallery-status').textContent=e.message}}
  $('add-gallery')?.addEventListener('click',uploadGallery);document.querySelector('.upload-drop')?.addEventListener('click',uploadGallery);document.querySelector('.upload-drop')?.addEventListener('dragover',e=>{e.preventDefault();e.currentTarget.classList.add('drag-active')});document.querySelector('.upload-drop')?.addEventListener('dragleave',e=>e.currentTarget.classList.remove('drag-active'));document.querySelector('.upload-drop')?.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();e.currentTarget.classList.remove('drag-active');saveDroppedGallery(e.dataTransfer?.files)});
  if($('count-reviews'))$('count-reviews').textContent='—';setupChecks();loadBlog();loadGallery();
})();