/* Estensione dei riquadri Lo Studio: mantiene i 4 esistenti e permette di aggiungerne altri. */
(function(){
  const API='/api/gallery',KEY='bruniano-studio-slot-count';
  let board=null,items=[],slotCount=4;
  const esc=v=>String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]));
  const technical=v=>{const s=String(v||'').trim();return !s||/\.(jpe?g|png|webp|avif|mp4|mov)$/i.test(s)||/^[A-Z0-9_-]{12,}(\.[A-Z0-9]+)?$/i.test(s)};
  async function api(method='GET',body){const r=await fetch(API+(method==='GET'?'?admin=1':''),{method,credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(r.status===401){location.replace('login.html');throw Error('Sessione scaduta')}if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
  const itemFor=s=>items.find(x=>Number(x.studio_slot)===s)||null;
  function syncCount(){const assigned=Math.max(4,...items.map(x=>Number(x.studio_slot)||0)),saved=Number(localStorage.getItem(KEY)||0);slotCount=Math.max(4,assigned,saved);localStorage.setItem(KEY,String(slotCount))}
  async function load(){try{items=(await api()).items||[];syncCount();wait()}catch(e){console.error('Studio load error',e)}}
  function wait(){const b=document.getElementById('studio-slot-board');if(b){board=b;install();return}setTimeout(wait,100)}
  function install(){if(!board)return;injectStyles();const head=board.closest('.studio-admin-card')?.querySelector('.studio-admin-card-head');if(head&&!document.getElementById('studio-add-slot')){const a=document.createElement('div');a.className='studio-extra-actions';a.innerHTML='<button class="mini" id="studio-add-slot" type="button">＋ Aggiungi riquadro</button><button class="primary" id="studio-upload-many" type="button">＋ Carica più foto</button>';head.appendChild(a);document.getElementById('studio-add-slot').onclick=addSlot;document.getElementById('studio-upload-many').onclick=uploadMany}render()}
  function render(){if(!board)return;const out=[];for(let s=1;s<=slotCount;s++){const m=itemFor(s),video=m&&String(m.media_type).startsWith('video'),desc=m&&!technical(m.title)?m.title:'';out.push(`<div class="studio-slot studio-slot-dynamic ${s===1?'large':''} ${s===4?'wide':''} ${m?'has-media':''}" data-dynamic-slot="${s}"><span class="studio-slot-label">RIQUADRO ${String(s).padStart(2,'0')}</span>${m?(video?`<video src="${esc(m.media_url)}" muted loop playsinline></video>`:`<img src="${esc(m.media_url)}" alt="${esc(m.alt_text||'')}">`):'<div class="studio-slot-empty">Trascina qui una foto dal catalogo<br>oppure usa “Carica foto”</div>'}${m&&desc?`<div class="studio-slot-overlay"><small>${esc(desc)}</small></div>`:''}<div class="studio-slot-actions-dynamic">${m?`<button type="button" data-save="${s}">Salva</button><button type="button" data-pub="${s}">${m.is_published?'Nascondi':'Pubblica'}</button><button type="button" data-clear="${s}">Togli</button>`:''}</div><div class="studio-slot-editor"><label>Descrizione<textarea data-desc="${s}" rows="2" maxlength="200" placeholder="Es. Sala di fisioterapia">${esc(desc)}</textarea></label>${m?'':'<button class="mini" data-upload="'+s+'" type="button">Carica foto</button>'}</div></div>`)}board.innerHTML=out.join('');bind()}
  function bind(){board.querySelectorAll('.studio-slot-dynamic').forEach(z=>{const s=Number(z.dataset.dynamicSlot);z.ondragover=e=>{e.preventDefault();z.classList.add('is-dragover')};z.ondragleave=()=>z.classList.remove('is-dragover');z.ondrop=e=>{e.preventDefault();z.classList.remove('is-dragover');const id=e.dataTransfer?.getData('text/plain');if(id)move(id,s)}});board.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(Number(b.dataset.save),b));board.querySelectorAll('[data-pub]').forEach(b=>b.onclick=()=>toggle(Number(b.dataset.pub)));board.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>clear(Number(b.dataset.clear)));board.querySelectorAll('[data-upload]').forEach(b=>b.onclick=()=>uploadOne(Number(b.dataset.upload)))}
  async function save(s,button){
    const m=itemFor(s); if(!m)return;
    const field=board.querySelector(`[data-desc="${s}"]`);
    const description=(field?.value||'').trim();
    if(description.length>200){alert('Descrizione troppo lunga (massimo 200 caratteri).');return}
    if(button)button.disabled=true;
    try{
      const result=await api('PUT',{id:m.id,title:description,media_type:m.media_type,media_url:m.media_url,alt_text:description||'Bruniano',sort_order:m.sort_order,studio_slot:s,is_published:m.is_published});
      if(!result?.id)throw new Error('Il server non ha confermato il salvataggio.');
      const fresh=await api('GET');
      items=fresh.items||[];
      syncCount();
      render();
      const saved=itemFor(s);
      const newField=board.querySelector(`[data-desc="${s}"]`);
      if(!saved || saved.title!==description || (newField?.value||'').trim()!==description){throw new Error('La descrizione non risulta salvata nel database.')}
      if(newField){newField.dataset.saved='1';newField.title='Salvato'}
      alert('Descrizione salvata.');
    }catch(e){alert(e.message||'Errore nel salvataggio della descrizione')}finally{if(button&&document.contains(button))button.disabled=false}
  }
  async function toggle(s){const m=itemFor(s);if(!m)return;try{const x=await api('PUT',{...m,id:m.id,is_published:!m.is_published,studio_slot:s});items=items.map(i=>i.id===x.id?x:i);render()}catch(e){alert(e.message)}}
  async function clear(s){const m=itemFor(s);if(!m)return;if(!confirm(`Togliere la foto dal riquadro ${s}? La foto resterà nel catalogo.`))return;try{const x=await api('PUT',{...m,id:m.id,studio_slot:null});items=items.map(i=>i.id===x.id?x:i);render();syncCount()}catch(e){alert(e.message)}}
  async function move(id,s){const m=items.find(i=>String(i.id)===String(id));if(!m)return;try{const x=await api('PUT',{...m,id:m.id,studio_slot:s,is_published:true});items=items.filter(i=>Number(i.studio_slot)!==s&&i.id!==x.id);items.push(x);if(s>slotCount){slotCount=s;localStorage.setItem(KEY,String(s))}render()}catch(e){alert(e.message)}}
  function addSlot(){slotCount++;localStorage.setItem(KEY,String(slotCount));render();setTimeout(()=>board.querySelector(`[data-dynamic-slot="${slotCount}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),30)}
  function cloud(){if(window.BrunianoCloudinary)return Promise.resolve(window.BrunianoCloudinary);return new Promise((ok,no)=>{const s=document.createElement('script');s.src='cloudinary-upload.js';s.onload=()=>window.BrunianoCloudinary?ok(window.BrunianoCloudinary):no(Error('Cloudinary non disponibile'));s.onerror=()=>no(Error('Impossibile caricare Cloudinary'));document.head.appendChild(s)})}
  function files(){return new Promise(ok=>{const i=document.createElement('input');i.type='file';i.multiple=true;i.accept='image/jpeg,image/png,image/webp,image/avif,video/mp4,video/quicktime';i.onchange=()=>ok(Array.from(i.files||[]));i.click()})}
  async function addInfo(info,s){const name=info.original_filename||info.display_name||'Foto Bruniano',x=await api('POST',{title:name,media_type:info.resource_type||'image',media_url:info.secure_url||info.url,alt_text:name,studio_slot:s,is_published:false});items=items.filter(i=>Number(i.studio_slot)!==s&&i.id!==x.id);items.push(x)}
  async function uploadOne(s){try{const c=await cloud();await c.uploadImage(info=>addInfo(info,s).then(()=>{if(s>slotCount){slotCount=s;localStorage.setItem(KEY,String(s))}render()}))}catch(e){alert(e.message||'Caricamento non riuscito')}}
  async function uploadMany(){try{const fs=await files();if(!fs.length)return;const c=await cloud();let s=1;while(itemFor(s))s++;slotCount=Math.max(slotCount,s+fs.length-1);localStorage.setItem(KEY,String(slotCount));let n=0;await c.uploadFiles(fs,async info=>{await addInfo(info,s+n);n++});render()}catch(e){alert(e.message||'Caricamento non riuscito')}}
  function injectStyles(){if(document.getElementById('studio-extra-slot-style'))return;const s=document.createElement('style');s.id='studio-extra-slot-style';s.textContent=`.studio-slot-dynamic{min-height:0;display:flex;flex-direction:column;justify-content:flex-end}.studio-slot-dynamic .studio-slot-editor{position:relative;z-index:5;padding:9px;background:rgba(255,255,255,.96);border-top:1px solid #dfe6ef}.studio-slot-dynamic .studio-slot-editor label{display:block;font-size:9px;font-weight:900;color:#475569}.studio-slot-dynamic .studio-slot-editor textarea{width:100%;box-sizing:border-box;margin-top:5px;border:1px solid #d7e0eb;border-radius:8px;padding:7px 8px;font:inherit;font-size:10px;resize:vertical;min-height:42px}.studio-slot-actions-dynamic{position:absolute;right:7px;top:7px;z-index:8;display:flex;gap:4px}.studio-slot-actions-dynamic button{border:1px solid rgba(255,255,255,.8);background:rgba(255,255,255,.96);color:#344054;border-radius:7px;padding:5px 6px;font-size:8px;font-weight:800;cursor:pointer}.studio-slot-actions-dynamic button:disabled{opacity:.55;cursor:wait}.studio-slot-dynamic.is-dragover{outline:3px solid rgba(21,92,255,.28);outline-offset:-3px}.studio-slot-dynamic .studio-slot-overlay{pointer-events:none;bottom:50px}.studio-slot-dynamic .studio-slot-overlay small{display:block;font-size:8px;line-height:1.3;opacity:.9;font-weight:700}.studio-extra-actions{display:flex;gap:7px;flex-wrap:wrap}.studio-extra-actions .mini,.studio-extra-actions .primary{white-space:nowrap}@media(max-width:650px){.studio-extra-actions{margin-top:10px}.studio-slot-dynamic .studio-slot-overlay{bottom:52px}}`;document.head.appendChild(s)}
  function init(){const p=document.getElementById('panel-gallery');if(!p)return;const t=p.querySelector('.gallery-toolbar');if(!t)return;injectStyles();load();const observer=new MutationObserver(()=>{const next=document.getElementById('studio-slot-board');if(next&&next!==board){board=next;install()}});observer.observe(p,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
