/* Estensione dei riquadri Lo Studio: mantiene i 4 esistenti e permette di aggiungerne altri. */
(function(){
  const API='/api/gallery';
  const STORAGE_KEY='bruniano-studio-slot-count';
  let board=null,items=[],slotCount=4,rendering=false;
  const esc=v=>String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]));
  const isTechnicalTitle=v=>{const s=String(v||'').trim();return !s||/\.(jpe?g|png|webp|avif|mp4|mov)$/i.test(s)||/^[A-Z0-9_-]{12,}(\.[A-Z0-9]+)?$/i.test(s)};
  async function api(method='GET',body){const r=await fetch(API+(method==='GET'?'?admin=1':''),{method,credentials:'same-origin',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(r.status===401){location.replace('login.html');throw new Error('Sessione scaduta')}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
  const itemFor=slot=>items.find(x=>Number(x.studio_slot)===slot)||null;
  function refreshCount(){const assigned=Math.max(4,...items.map(x=>Number(x.studio_slot)||0));const saved=Number(localStorage.getItem(STORAGE_KEY)||0);slotCount=Math.max(assigned,saved,4);localStorage.setItem(STORAGE_KEY,String(slotCount));}
  async function load(){try{items=(await api()).items||[];refreshCount();waitForBoard();}catch{}}
  function waitForBoard(){const found=document.getElementById('studio-slot-board');if(found){board=found;install();return}setTimeout(waitForBoard,100)}
  function install(){if(!board)return;if(!document.getElementById('studio-extra-slot-style'))injectStyles();const head=board.closest('.studio-admin-card')?.querySelector('.studio-admin-card-head');if(head&&!document.getElementById('studio-add-slot')){const actions=document.createElement('div');actions.className='studio-extra-actions';actions.innerHTML='<button class="mini" id="studio-add-slot" type="button">＋ Aggiungi riquadro</button><button class="primary" id="studio-upload-many" type="button">＋ Carica più foto</button>';head.appendChild(actions);document.getElementById('studio-add-slot').addEventListener('click',addSlot);document.getElementById('studio-upload-many').addEventListener('click',uploadMany)}if(board.dataset.dynamic==='1')return;board.dataset.dynamic='1';render();const observer=new MutationObserver(()=>{if(rendering)return;setTimeout(()=>{if(board&&!board.dataset.internalUpdate)render()},0)});observer.observe(board,{childList:true,subtree:true})}
  function render(){if(!board||rendering)return;rendering=true;board.dataset.internalUpdate='1';const html=[];for(let slot=1;slot<=slotCount;slot++){const item=itemFor(slot),video=item&&String(item.media_type).startsWith('video'),description=item&&!isTechnicalTitle(item.title)?item.title:'';html.push(`<div class="studio-slot studio-slot-dynamic ${slot===1?'large':''} ${slot===4?'wide':''} ${item?'has-media':''}" data-dynamic-slot="${slot}"><span class="studio-slot-label">RIQUADRO ${String(slot).padStart(2,'0')}</span>${item?(video?`<video src="${esc(item.media_url)}" muted loop playsinline></video>`:`<img src="${esc(item.media_url)}" alt="${esc(item.alt_text||'')}">`):'<div class="studio-slot-empty">Trascina qui una foto dal catalogo<br>oppure usa “Carica foto”</div>'}${item?`<div class="studio-slot-overlay"><strong>${esc(description||'Foto senza descrizione')}</strong><small>Posizione ${slot}</small></div>`:''}<div class="studio-slot-actions-dynamic">${item?`<button type="button" data-slot-save="${slot}">Salva</button><button type="button" data-slot-publish="${slot}">${item.is_published?'Nascondi':'Pubblica'}</button><button type="button" data-slot-clear="${slot}">Togli</button>`:''}</div><div class="studio-slot-editor"><label>Descrizione<textarea data-slot-description="${slot}" rows="2" placeholder="Es. Sala di fisioterapia">${esc(description)}</textarea></label>${item?'':'<button class="mini studio-slot-upload" type="button" data-slot-upload="'+slot+'">Carica foto</button>'}</div></div>`)}board.innerHTML=html.join('');board.dataset.internalUpdate='';rendering=false;bindBoard()}
  function bindBoard(){board.querySelectorAll('.studio-slot-dynamic').forEach(zone=>{const slot=Number(zone.dataset.dynamicSlot);zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('is-dragover')});zone.addEventListener('dragleave',()=>zone.classList.remove('is-dragover'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('is-dragover');const id=e.dataTransfer?.getData('text/plain');if(id)moveMedia(id,slot)})});board.querySelectorAll('[data-slot-save]').forEach(b=>b.addEventListener('click',()=>saveSlot(Number(b.dataset.slotSave))));board.querySelectorAll('[data-slot-publish]').forEach(b=>b.addEventListener('click',()=>toggleSlot(Number(b.dataset.slotPublish))));board.querySelectorAll('[data-slot-clear]').forEach(b=>b.addEventListener('click',()=>clearSlot(Number(b.dataset.slotClear))));board.querySelectorAll('[data-slot-upload]').forEach(b=>b.addEventListener('click',()=>uploadInto(Number(b.dataset.slotUpload))))}
  async function saveSlot(slot){const item=itemFor(slot);if(!item)return;const title=board.querySelector(`[data-slot-description="${slot}"]`)?.value.trim()||'';try{const saved=await api('PUT',{...item,id:item.id,title,alt_text:title||item.alt_text||'Bruniano',studio_slot:slot});items=items.map(x=>x.id===saved.id?saved:x);render()}catch(e){alert(e.message)}}
  async function toggleSlot(slot){const item=itemFor(slot);if(!item)return;try{const saved=await api('PUT',{...item,id:item.id,is_published:!item.is_published,studio_slot:slot});items=items.map(x=>x.id===saved.id?saved:x);render()}catch(e){alert(e.message)}}
  async function clearSlot(slot){const item=itemFor(slot);if(!item)return;if(!confirm(`Togliere la foto dal riquadro ${slot}? La foto resterà nel catalogo.`))return;try{const saved=await api('PUT',{...item,id:item.id,studio_slot:null});items=items.map(x=>x.id===saved.id?saved:x);render();refreshCount()}catch(e){alert(e.message)}}
  async function moveMedia(id,slot){const item=items.find(x=>String(x.id)===String(id));if(!item)return;try{const saved=await api('PUT',{...item,id:item.id,studio_slot:slot,is_published:true});items=items.filter(x=>Number(x.studio_slot)!==slot&&x.id!==saved.id);items.push(saved);ensureSlot(slot);render()}catch(e){alert(e.message)}}
  function ensureSlot(slot){if(slot>slotCount){slotCount=slot;localStorage.setItem(STORAGE_KEY,String(slotCount))}}
  function addSlot(){slotCount++;localStorage.setItem(STORAGE_KEY,String(slotCount));render();setTimeout(()=>board.querySelector(`[data-dynamic-slot="${slotCount}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),30)}
  function cloudinary(){if(window.BrunianoCloudinary)return Promise.resolve(window.BrunianoCloudinary);return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='cloudinary-upload.js';s.onload=()=>window.BrunianoCloudinary?resolve(window.BrunianoCloudinary):reject(new Error('Cloudinary non disponibile'));s.onerror=()=>reject(new Error('Impossibile caricare Cloudinary'));document.head.appendChild(s)})}
  function chooseFiles(){return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.multiple=true;input.accept='image/jpeg,image/png,image/webp,image/avif,video/mp4,video/quicktime';input.onchange=()=>resolve(Array.from(input.files||[]));input.click()})}
  async function createFromInfo(info,slot){const name=info.original_filename||info.display_name||'Foto Bruniano';const saved=await api('POST',{title:name,media_type:info.resource_type||'image',media_url:info.secure_url||info.url,alt_text:name,studio_slot:slot,is_published:false});items=items.filter(x=>Number(x.studio_slot)!==slot&&x.id!==saved.id);items.push(saved);return saved}
  async function uploadInto(slot){try{const cloud=await cloudinary();await cloud.uploadImage(info=>{createFromInfo(info,slot).then(()=>{ensureSlot(slot);render()})})}catch(e){alert(e.message||'Caricamento non riuscito')}}
  async function uploadMany(){try{const files=await chooseFiles();if(!files.length)return;const cloud=await cloudinary();let target=1;while(itemFor(target))target++;ensureSlot(target+files.length-1);let i=0;await cloud.uploadFiles(files,async info=>{await createFromInfo(info,target+i);i++});render()}catch(e){alert(e.message||'Caricamento non riuscito')}}
  function injectStyles(){const s=document.createElement('style');s.id='studio-extra-slot-style';s.textContent=`.studio-slot-dynamic{min-height:0;display:flex;flex-direction:column;justify-content:flex-end}.studio-slot-dynamic .studio-slot-editor{position:relative;z-index:5;padding:9px;background:rgba(255,255,255,.96);border-top:1px solid #dfe6ef}.studio-slot-dynamic .studio-slot-editor label{display:block;font-size:9px;font-weight:900;color:#475569}.studio-slot-dynamic .studio-slot-editor textarea{width:100%;box-sizing:border-box;margin-top:5px;border:1px solid #d7e0eb;border-radius:8px;padding:7px 8px;font:inherit;font-size:10px;resize:vertical;min-height:42px}.studio-slot-actions-dynamic{position:absolute;right:7px;top:7px;z-index:8;display:flex;gap:4px}.studio-slot-actions-dynamic button{border:1px solid rgba(255,255,255,.8);background:rgba(255,255,255,.96);color:#344054;border-radius:7px;padding:5px 6px;font-size:8px;font-weight:800;cursor:pointer}.studio-slot-actions-dynamic button:hover{color:#155cff}.studio-slot-dynamic.is-dragover{outline:3px solid rgba(21,92,255,.28);outline-offset:-3px}.studio-slot-dynamic .studio-slot-overlay{pointer-events:none;bottom:76px}.studio-extra-actions{display:flex;gap:7px;flex-wrap:wrap}.studio-extra-actions .mini,.studio-extra-actions .primary{white-space:nowrap}@media(max-width:650px){.studio-extra-actions{margin-top:10px}.studio-slot-dynamic .studio-slot-overlay{bottom:82px}}`;document.head.appendChild(s)}
  function enhanceLibraryCards(){document.querySelectorAll('#gallery-list .media-admin-card').forEach(card=>{if(card.dataset.studioDragEnhanced)return;const del=card.querySelector('[data-gallery-delete]'),toggle=card.querySelector('[data-gallery-toggle]'),id=del?.dataset.galleryDelete||toggle?.dataset.galleryToggle;if(!id)return;card.dataset.studioDragEnhanced='1';card.draggable=true;card.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='move'})})}
  function init(){const panel=document.getElementById('panel-gallery');if(!panel)return;const toolbar=panel.querySelector('.gallery-toolbar');if(!toolbar)return;injectStyles();load();const observer=new MutationObserver(()=>{enhanceLibraryCards();const next=document.getElementById('studio-slot-board');if(next&&next!==board){board=next;install()}});observer.observe(panel,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
