const teamState={items:[]};
const team$=id=>document.getElementById(id);
const teamEsc=v=>String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]));
async function teamApi(url,options={}){const r=await fetch(url,{headers:{'content-type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function ensureCloudinary(){return new Promise((resolve,reject)=>{if(window.BrunianoCloudinary)return resolve();const s=document.createElement('script');s.src='../admin/cloudinary-upload.js';s.onload=()=>window.BrunianoCloudinary?resolve():reject(new Error('Cloudinary upload helper non disponibile'));s.onerror=()=>reject(new Error('Impossibile caricare il caricamento Cloudinary'));document.head.appendChild(s)})}
async function uploadPhoto(inputId,statusId){try{await ensureCloudinary();const status=team$(statusId);status.textContent='Apertura caricamento…';await window.BrunianoCloudinary.uploadImage(info=>{team$(inputId).value=info.secure_url||info.url||'';status.textContent='Foto caricata su Cloudinary'});}catch(e){team$(statusId).textContent=e.message}}
function teamForm(item={}){const c=item.curriculum||{};team$('team-form').innerHTML=`<div class="panel-title"><div><p>SCHEDA PROFESSIONISTA</p><h3>${item.id?'Modifica professionista':'Nuovo professionista'}</h3></div><button class="mini" type="button" id="team-cancel">Annulla</button></div><form id="team-editor"><input type="hidden" id="team-id" value="${teamEsc(item.id||'')}"><div class="form-row"><label>Nome e cognome<input id="team-name" required value="${teamEsc(item.name||'')}"></label><label>Qualifica<input id="team-role" value="${teamEsc(item.role||'')}"></label></div><div class="form-row"><label>Specializzazione<input id="team-specialty" value="${teamEsc(item.specialty||'')}"></label><label>Ordine<input id="team-order" type="number" value="${Number(item.sort_order||0)}"></label></div><label>Foto del professionista<div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><input id="team-photo" value="${teamEsc(item.photo_url||'')}" placeholder="Il link Cloudinary verrà inserito qui" style="flex:1;min-width:240px"><button class="mini" type="button" id="team-photo-upload">Carica foto</button></div><small id="team-photo-status" style="display:block;margin-top:6px;color:#657083">La foto viene caricata su Cloudinary; il sito salva solo il link.</small></label><label>Breve presentazione<textarea id="team-bio" rows="3">${teamEsc(item.bio||'')}</textarea></label><div class="form-card note"><strong>Curriculum</strong><span>Questi dati compaiono solo quando il visitatore apre la scheda Curriculum.</span></div><label>Profilo professionale<textarea id="cv-profile" rows="4">${teamEsc(c.profile||'')}</textarea></label><label>Formazione<textarea id="cv-training" rows="4">${teamEsc(c.training||'')}</textarea></label><label>Esperienza professionale<textarea id="cv-experience" rows="4">${teamEsc(c.experience||'')}</textarea></label><label>Certificazioni e competenze<textarea id="cv-certifications" rows="4">${teamEsc(c.certifications||'')}</textarea></label><label class="check-inline"><input id="team-published" type="checkbox" ${item.is_published?'checked':''}> Pubblica sul sito</label><div class="form-actions"><button class="primary" type="submit">Salva professionista</button><span id="team-status"></span></div></form>`;team$('team-cancel').onclick=()=>team$('team-form').classList.add('hidden');team$('team-photo-upload').onclick=()=>uploadPhoto('team-photo','team-photo-status');team$('team-editor').onsubmit=saveTeam}
function renderTeam(){const list=team$('team-list');list.innerHTML=teamState.items.length?teamState.items.map(m=>`<div class="managed-item"><div style="display:flex;gap:12px;align-items:center">${m.photo_url?`<img src="${m.photo_url}" alt="" style="width:54px;height:54px;object-fit:cover;border-radius:12px">`:''}<div><strong>${teamEsc(m.name)}</strong><small>${teamEsc(m.role)} · ${teamEsc(m.specialty)} · ${m.is_published?'Pubblicato':'Bozza'}</small></div></div><div class="managed-actions"><button class="mini" data-team-edit="${m.id}">Modifica</button><button class="mini" data-team-delete="${m.id}">Elimina</button></div></div>`).join(''):'<div class="form-card note">Nessun professionista presente.</div>';team$('count-team').textContent=teamState.items.length}
async function loadTeam(){try{const d=await teamApi('/api/team?admin=1');teamState.items=d.items||[];renderTeam();document.getElementById('system-status').textContent='Backend collegato'}catch(e){team$('team-list').innerHTML='<div class="form-card note">Backend Team non disponibile.</div>';document.getElementById('system-status').textContent='Backend non configurato'}}
async function saveTeam(e){e.preventDefault();const id=team$('team-id').value||undefined;const payload={id,name:team$('team-name').value,role:team$('team-role').value,specialty:team$('team-specialty').value,photo_url:team$('team-photo').value,bio:team$('team-bio').value,sort_order:Number(team$('team-order').value||0),is_published:team$('team-published').checked,curriculum:{profile:team$('cv-profile').value,training:team$('cv-training').value,experience:team$('cv-experience').value,certifications:team$('cv-certifications').value}};try{const saved=await teamApi('/api/team',{method:id?'PUT':'POST',body:JSON.stringify(payload)});const i=teamState.items.findIndex(x=>x.id===saved.id);if(i>=0)teamState.items[i]=saved;else teamState.items.push(saved);renderTeam();teamForm(saved);team$('team-status').textContent='Professionista salvato'}catch(e){team$('team-status').textContent=e.message}}
document.addEventListener('click',async e=>{const edit=e.target.closest('[data-team-edit]'),del=e.target.closest('[data-team-delete]');if(edit){teamForm(teamState.items.find(x=>x.id===edit.dataset.teamEdit));team$('team-form').classList.remove('hidden');team$('team-form').scrollIntoView({behavior:'smooth'})}if(del){if(!confirm('Eliminare definitivamente questo professionista?'))return;try{await teamApi('/api/team',{method:'DELETE',body:JSON.stringify({id:del.dataset.teamDelete})});teamState.items=teamState.items.filter(x=>x.id!==del.dataset.teamDelete);renderTeam()}catch(err){alert(err.message)}}});
const addTeamReal=document.getElementById('add-team');if(addTeamReal)addTeamReal.onclick=()=>{teamForm();team$('team-form').classList.remove('hidden');team$('team-form').scrollIntoView({behavior:'smooth'})};
loadTeam();

async function setupGalleryCloudinary(){const drop=document.querySelector('.upload-drop');if(!drop)return;try{await ensureCloudinary()}catch(e){drop.querySelector('span').textContent=e.message;return}drop.innerHTML='<strong>Trascina qui foto e video</strong><span>oppure tocca per scegliere dal PC</span><button class="primary" type="button" id="cloudinary-gallery-upload">Carica media</button><small id="gallery-upload-status" style="display:block;margin-top:8px;color:#657083">I file vengono caricati su Cloudinary; nel CMS salviamo solo i link.</small>';const open=()=>window.BrunianoCloudinary.uploadMedia(async info=>{const status=document.getElementById('gallery-upload-status');status.textContent='Caricamento completato';try{await fetch('../api/gallery',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:info.original_filename||info.display_name||'Media Bruniano',media_type:info.resource_type||'image',media_url:info.secure_url||info.url,alt_text:info.original_filename||'Media Bruniano',is_published:false})});status.textContent='Media caricato su Cloudinary e salvato nel CMS'}catch(e){status.textContent='File su Cloudinary, ma salvataggio CMS non riuscito';console.error(e)}});document.getElementById('cloudinary-gallery-upload')?.addEventListener('click',open);drop.addEventListener('click',e=>{if(e.target===drop||e.target.closest('strong')||e.target.closest('span'))open()});drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-active')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag-active'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag-active');open()})}
setupGalleryCloudinary();
