import { db, send, getQuery } from './_db.js';
import { requireAdmin } from './_auth.js';
const LIMITS={title:200,subtitle:300,description:5000,image:2048,whatsapp:1000,cta:100};
class ValidationError extends Error{}
function text(value,max,field,required=false){const v=String(value??'').trim();if(required&&!v)throw new ValidationError(`${field} obbligatorio`);if(v.length>max)throw new ValidationError(`${field} troppo lungo`);return v}
function url(value){const v=text(value,LIMITS.image,'URL immagine');if(!v)return '';let u;try{u=new URL(v)}catch{throw new ValidationError('URL immagine non valido')}if(u.protocol!=='https:')throw new ValidationError('URL immagine deve usare HTTPS');return u.toString()}
function date(value){if(!value)return null;const d=new Date(value);if(Number.isNaN(d.getTime()))throw new ValidationError('Data non valida');return d.toISOString()}
async function ensurePromotionSchema(sql){
 await sql`CREATE TABLE IF NOT EXISTS promotions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),title text NOT NULL,description text,image_url text,starts_at timestamptz,ends_at timestamptz,whatsapp_message text,is_published boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`;
 await sql`ALTER TABLE promotions ADD COLUMN IF NOT EXISTS subtitle text`;
 await sql`ALTER TABLE promotions ADD COLUMN IF NOT EXISTS cta_label text`;
 await sql`ALTER TABLE promotions ADD COLUMN IF NOT EXISTS page_published boolean NOT NULL DEFAULT true`;
 await sql`ALTER TABLE promotions ADD COLUMN IF NOT EXISTS show_home_top boolean NOT NULL DEFAULT false`;
 await sql`ALTER TABLE promotions ADD COLUMN IF NOT EXISTS show_home_center boolean NOT NULL DEFAULT false`;
 await sql`ALTER TABLE promotions ADD COLUMN IF NOT EXISTS home_top_order integer NOT NULL DEFAULT 0`;
 await sql`ALTER TABLE promotions ADD COLUMN IF NOT EXISTS home_center_order integer NOT NULL DEFAULT 0`;
}
export default async function handler(req,res){try{const sql=db();await ensurePromotionSchema(sql);
 if(req.method==='GET'){const admin=getQuery(req).admin==='1';if(admin){if(!(await requireAdmin(req,res)))return;const rows=await sql`SELECT id,title,subtitle,description,image_url,starts_at,ends_at,whatsapp_message,cta_label,is_published,page_published,show_home_top,show_home_center,home_top_order,home_center_order,created_at,updated_at FROM promotions ORDER BY created_at DESC`;return send(res,{items:rows})}const rows=await sql`SELECT id,title,subtitle,description,image_url,starts_at,ends_at,whatsapp_message,cta_label,page_published,show_home_top,show_home_center,home_top_order,home_center_order FROM promotions WHERE is_published=true AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>=now()) AND (page_published=true OR show_home_top=true OR show_home_center=true) ORDER BY created_at DESC`;return send(res,{items:rows})}
 if(!(await requireAdmin(req,res)))return;const body=req.body||{};
 if(req.method==='POST'||req.method==='PUT'){const id=body.id||null,title=text(body.title,LIMITS.title,'Titolo',true),subtitle=text(body.subtitle,LIMITS.subtitle,'Sottotitolo'),description=text(body.description,LIMITS.description,'Descrizione'),imageUrl=url(body.image_url),whatsapp=text(body.whatsapp_message,LIMITS.whatsapp,'Messaggio WhatsApp'),cta=text(body.cta_label,LIMITS.cta,'Testo pulsante')||"Scopri l'offerta",startsAt=date(body.starts_at),endsAt=date(body.ends_at);if(startsAt&&endsAt&&new Date(startsAt)>new Date(endsAt))throw new ValidationError('La data di fine deve essere successiva alla data di inizio');const published=Boolean(body.is_published),page=Boolean(body.page_published),top=Boolean(body.show_home_top),center=Boolean(body.show_home_center),topOrder=Number.isInteger(Number(body.home_top_order))?Number(body.home_top_order):0,centerOrder=Number.isInteger(Number(body.home_center_order))?Number(body.home_center_order):0;let rows;if(id)rows=await sql`UPDATE promotions SET title=${title},subtitle=${subtitle},description=${description},image_url=${imageUrl},starts_at=${startsAt},ends_at=${endsAt},whatsapp_message=${whatsapp},cta_label=${cta},is_published=${published},page_published=${page},show_home_top=${top},show_home_center=${center},home_top_order=${topOrder},home_center_order=${centerOrder},updated_at=now() WHERE id=${id} RETURNING *`;else rows=await sql`INSERT INTO promotions(title,subtitle,description,image_url,starts_at,ends_at,whatsapp_message,cta_label,is_published,page_published,show_home_top,show_home_center,home_top_order,home_center_order) VALUES(${title},${subtitle},${description},${imageUrl},${startsAt},${endsAt},${whatsapp},${cta},${published},${page},${top},${center},${topOrder},${centerOrder}) RETURNING *`;return rows[0]?send(res,rows[0],id?200:201):send(res,{error:'Promozione non trovata'},404)}
 if(req.method==='DELETE'){if(!body.id)return send(res,{error:'ID obbligatorio'},400);const rows=await sql`DELETE FROM promotions WHERE id=${body.id} RETURNING id`;return rows[0]?send(res,{ok:true}):send(res,{error:'Promozione non trovata'},404)}res.setHeader('Allow','GET,POST,PUT,DELETE');return send(res,{error:'Method not allowed'},405)}catch(error){console.error('Promotions API error:',error);if(error instanceof ValidationError)return send(res,{error:error.message},400);return send(res,{error:'Errore nella gestione delle promozioni'},500)}}
